class SearchSource {
	async data() {
		return {
			layout: "searchable.11ty.js",
			// permalink: false,
			permalink: "searchsource.json",
		};
	}
	dataset(songs) {
		return songs.map((song) => {
			return {
				id: song.template.filePathStem,
				full_text: song.content,
				title: song.data.title,
				description: song.data.description,
				artists: song.data.artists.join(", "),
				album: song.data.album,
				tags: song.data.tags.join(" "),
				date: song.data.date,
				slug: song.template.fileSlugStr,
			};
		});
	}
	async render(data) {
		//console.log("search data", data.collections.songs);
		return JSON.stringify(this.dataset(data.collections.songs));
	}
}

module.exports = SearchSource;

/** 
 * 
    data: {
      me: [Object],
      metadata: [Object],
      site: [Object],
      eleventy: [Object],
      pkg: [Object],
      layout: 'song.11ty.js',
      description: '',
      tags: [Array],
      date: 2023-08-30T21:06:40.000Z,
      title: 'Su Beso de Plata - Redux by Carlos Viola',
      public: true,
      artists: [Array],
      songtitle: 'Su Beso de Plata - Redux',
      album: 'Blasphemous: Wounds of Eventide (Original Game Soundtrack)',
      featuredImage: 'su-beso-de-plata-redux-by-carlos-viola.jpeg',
      featuredImageCredit: 'Image is used from album for review purposes.',
      featuredImageLink: 'su-beso-de-plata-redux-by-carlos-viola.jpeg',
      featuredImageAlt: '',
      playlists: [Array],
      youtube: 'https://www.youtube.com/watch?v=CO218kSZoeA',
      spotify: 'https://open.spotify.com/track/35qkwnnlbohFTDGUaOKhCT',
      soundcloud: null,
      audiofile: null,
      lastfm: 'https://www.last.fm/music/Carlos+Viola/_/Su+Beso+de+Plata+-+Redux',
      page: [Object],
      collections: [Object]
    },
    page: {
      date: 2023-08-30T21:06:40.000Z,
      inputPath: './src/songs/su-beso-de-plata-redux-by-carlos-viola.md',
      fileSlug: 'su-beso-de-plata-redux-by-carlos-viola',
      filePathStem: '/songs/su-beso-de-plata-redux-by-carlos-viola',
      outputFileExtension: 'html',
      templateSyntax: 'liquid,md',
      url: '/songs/su-beso-de-plata-redux-by-carlos-viola/',
      outputPath: 'docs/songs/su-beso-de-plata-redux-by-carlos-viola/index.html'
    },
    inputPath: './src/songs/su-beso-de-plata-redux-by-carlos-viola.md',
    fileSlug: 'su-beso-de-plata-redux-by-carlos-viola',
    filePathStem: '/songs/su-beso-de-plata-redux-by-carlos-viola',
    date: 2023-08-30T21:06:40.000Z,
    outputPath: 'docs/songs/su-beso-de-plata-redux-by-carlos-viola/index.html',
    url: '/songs/su-beso-de-plata-redux-by-carlos-viola/',
    templateContent: [Getter/Setter],
    content: [Getter]
  },
  {
    template: Template {
      _config: [TemplateConfig],
      _configOptions: [Object],
      inputPath: './src/songs/the-root-by-magna-carda.md',
      inputDir: 'src',
      parsed: [Object],
      extraOutputSubdirectory: '',
      outputDir: 'docs',
      _extensionMap: [EleventyExtensionMap],
      linters: [],
      transforms: [],
      templateData: [TemplateData],
      isVerbose: false,
      isDryRun: false,
      writeCount: 0,
      fileSlug: [TemplateFileSlug],
      fileSlugStr: 'the-root-by-magna-carda',
      filePathStem: '/songs/the-root-by-magna-carda',
      outputFormat: 'fs',
      behavior: [TemplateBehavior],
      serverlessUrls: null,
      _logger: [ConsoleLogger],
      _templateRender: [TemplateRender],
      inputContent: [Promise],
      readingPromise: [Promise],
      _frontMatterDataCache: [Promise],
      _frontMatter: [Object],
      _dataCache: [Object],
      _usePermalinkRoot: undefined
    },
    data: {
      me: [Object],
      metadata: [Object],
      site: [Object],
      eleventy: [Object],
      pkg: [Object],
      layout: 'song.11ty.js',
      description: '',
      tags: [Array],
      date: 2023-08-30T21:06:51.000Z,
      title: 'The Root by Magna Carda',
      public: true,
      artists: [Array],
      songtitle: 'The Root',
      album: 'Cirqlation',
      featuredImage: 'the-root-by-magna-carda.jpeg',
      featuredImageCredit: 'Image is used from album for review purposes.',
      featuredImageLink: 'the-root-by-magna-carda.jpeg',
      featuredImageAlt: '',
      playlists: [Array],
      youtube: 'https://www.youtube.com/watch?v=Mbzqfdqnt_o',
      spotify: 'https://open.spotify.com/track/21sficAs0W3Swr2kyQ75ps',
      soundcloud: null,
      audiofile: null,
      lastfm: 'https://www.last.fm/music/Magna+Carda/_/The+Root',
      page: [Object],
      collections: [Object]
    },
    page: {
      date: 2023-08-30T21:06:51.000Z,
      inputPath: './src/songs/the-root-by-magna-carda.md',
      fileSlug: 'the-root-by-magna-carda',
      filePathStem: '/songs/the-root-by-magna-carda',
      outputFileExtension: 'html',
      templateSyntax: 'liquid,md',
      url: '/songs/the-root-by-magna-carda/',
      outputPath: 'docs/songs/the-root-by-magna-carda/index.html'
    },
    inputPath: './src/songs/the-root-by-magna-carda.md',
    fileSlug: 'the-root-by-magna-carda',
    filePathStem: '/songs/the-root-by-magna-carda',
    date: 2023-08-30T21:06:51.000Z,
    outputPath: 'docs/songs/the-root-by-magna-carda/index.html',
    url: '/songs/the-root-by-magna-carda/',
    templateContent: [Getter/Setter],
    content: [Getter]
  },
  {
    template: Template {
      _config: [TemplateConfig],
      _configOptions: [Object],
      inputPath: './src/songs/new-york-by-angel-haze.md',
      inputDir: 'src',
      parsed: [Object],
      extraOutputSubdirectory: '',
      outputDir: 'docs',
      _extensionMap: [EleventyExtensionMap],
      linters: [],
      transforms: [],
      templateData: [TemplateData],
      isVerbose: false,
      isDryRun: false,
      writeCount: 0,
      fileSlug: [TemplateFileSlug],
      fileSlugStr: 'new-york-by-angel-haze',
      filePathStem: '/songs/new-york-by-angel-haze',
      outputFormat: 'fs',
      behavior: [TemplateBehavior],
      serverlessUrls: null,
      _logger: [ConsoleLogger],
      _templateRender: [TemplateRender],
      inputContent: [Promise],
      readingPromise: [Promise],
      _frontMatterDataCache: [Promise],
      _frontMatter: [Object],
      _dataCache: [Object],
      _usePermalinkRoot: undefined
    },
    data: {
      me: [Object],
      metadata: [Object],
      site: [Object],
      eleventy: [Object],
      pkg: [Object],
      layout: 'song.11ty.js',
      description: '',
      tags: [Array],
      date: 2023-08-31T15:40:54.000Z,
      title: 'New York by Angel Haze',
      public: true,
      artists: [Array],
      songtitle: 'New York',
      album: 'Dirty Gold (Deluxe)',
      featuredImage: 'new-york-by-angel-haze.jpeg',
      featuredImageCredit: 'Image is used from album for review purposes.',
      featuredImageLink: 'new-york-by-angel-haze.jpeg',
      featuredImageAlt: '',
      playlists: [Array],
      youtube: 'https://www.youtube.com/watch?v=4hKP5ljDar8',
      spotify: 'https://open.spotify.com/track/15mKdoeoLQr6F8cFdko7Aa',
      soundcloud: null,
      audiofile: null,
      lastfm: 'https://www.last.fm/music/Angel+Haze/_/New+York',
      page: [Object],
      collections: [Object]
    },
    page: {
      date: 2023-08-31T15:40:54.000Z,
      inputPath: './src/songs/new-york-by-angel-haze.md',
      fileSlug: 'new-york-by-angel-haze',
      filePathStem: '/songs/new-york-by-angel-haze',
      outputFileExtension: 'html',
      templateSyntax: 'liquid,md',
      url: '/songs/new-york-by-angel-haze/',
      outputPath: 'docs/songs/new-york-by-angel-haze/index.html'
    },
    inputPath: './src/songs/new-york-by-angel-haze.md',
    fileSlug: 'new-york-by-angel-haze',
    filePathStem: '/songs/new-york-by-angel-haze',
    date: 2023-08-31T15:40:54.000Z,
    outputPath: 'docs/songs/new-york-by-angel-haze/index.html',
    url: '/songs/new-york-by-angel-haze/',
    templateContent: [Getter/Setter],
    content: [Getter]
  }
]
[11ty] Copied 42 files / Wrote 17 files in 0.43 seconds (25.3ms each, v2.0.1)
[11ty] Watching…
[11ty] File changed: src/searchsource.11ty.js
songPages New York by Angel Haze [{"name":"Obsessions","position":429,"author":"Aram Zucker-Scharff"}]
songPages The Root by Magna Carda [{"name":"Obsessions","position":428,"author":"Aram Zucker-Scharff"}]
songPages Su Beso de Plata - Redux by Carlos Viola [{"name":"Obsessions","position":427,"author":"Aram Zucker-Scharff"}]
search data [
  {
    template: Template {
      _config: [TemplateConfig],
      _configOptions: [Object],
      inputPath: './src/songs/black-nightacoustic-circus-by-strawberry-girls.md',
      inputDir: 'src',
      parsed: [Object],
      extraOutputSubdirectory: '',
      outputDir: 'docs',
      _extensionMap: [EleventyExtensionMap],
      linters: [],
      transforms: [],
      templateData: [TemplateData],
      isVerbose: false,
      isDryRun: false,
      writeCount: 0,
      fileSlug: [TemplateFileSlug],
      fileSlugStr: 'black-nightacoustic-circus-by-strawberry-girls',
      filePathStem: '/songs/black-nightacoustic-circus-by-strawberry-girls',
      outputFormat: 'fs',
      behavior: [TemplateBehavior],
      serverlessUrls: null,
      _logger: [ConsoleLogger],
      _templateRender: [TemplateRender],
      _frontMatter: [Object],
      _usePermalinkRoot: undefined,
      inputContent: [Promise],
      readingPromise: [Promise],
      _frontMatterDataCache: [Promise],
      _dataCache: [Object]
    },
    data: {
      me: [Object],
      metadata: [Object],
      site: [Object],
      eleventy: [Object],
      pkg: [Object],
      layout: 'song.11ty.js',
      description: '',
      tags: [Array],
      date: 2023-08-22T16:39:14.000Z,
      title: 'Black Night/Acoustic Circus by Strawberry Girls',
      public: true,
      artists: [Array],
      songtitle: 'Black Night/Acoustic Circus',
      album: 'Acoustic Ghosts',
      featuredImage: 'black-nightacoustic-circus-by-strawberry-girls.jpeg',
      featuredImageCredit: 'Image is used from album for review purposes.',
      featuredImageLink: 'black-nightacoustic-circus-by-strawberry-girls.jpeg',
      featuredImageAlt: '',
      playlists: [Array],
      youtube: 'https://www.youtube.com/watch?v=rBhGmaUQLuw',
      spotify: 'https://open.spotify.com/track/5mNbGr1hFdyXdEeIlJAkK9',
      soundcloud: null,
      audiofile: null,
      lastfm: 'https://www.last.fm/music/Strawberry+Girls/_/Black+Night%2FAcoustic+Circus',
      page: [Object],
      collections: [Object]
    },
    page: {
      date: 2023-08-22T16:39:14.000Z,
      inputPath: './src/songs/black-nightacoustic-circus-by-strawberry-girls.md',
      fileSlug: 'black-nightacoustic-circus-by-strawberry-girls',
      filePathStem: '/songs/black-nightacoustic-circus-by-strawberry-girls',
      outputFileExtension: 'html',
      templateSyntax: 'liquid,md',
      url: '/songs/black-nightacoustic-circus-by-strawberry-girls/',
      outputPath: 'docs/songs/black-nightacoustic-circus-by-strawberry-girls/index.html'
    },
    inputPath: './src/songs/black-nightacoustic-circus-by-strawberry-girls.md',
    fileSlug: 'black-nightacoustic-circus-by-strawberry-girls',
    filePathStem: '/songs/black-nightacoustic-circus-by-strawberry-girls',
    date: 2023-08-22T16:39:14.000Z,
    outputPath: 'docs/songs/black-nightacoustic-circus-by-strawberry-girls/index.html',
    url: '/songs/black-nightacoustic-circus-by-strawberry-girls/',
    templateContent: [Getter/Setter],
    content: [Getter]
  },
  {
    template: Template {
      _config: [TemplateConfig],
      _configOptions: [Object],
      inputPath: './src/songs/when-the-catholic-girls-go-camping-the-nicotine-vampires-rule-supreme-by-giraffes-giraffes.md',
      inputDir: 'src',
      parsed: [Object],
      extraOutputSubdirectory: '',
      outputDir: 'docs',
      _extensionMap: [EleventyExtensionMap],
      linters: [],
      transforms: [],
      templateData: [TemplateData],
      isVerbose: false,
      isDryRun: false,
      writeCount: 0,
      fileSlug: [TemplateFileSlug],
      fileSlugStr: 'when-the-catholic-girls-go-camping-the-nicotine-vampires-rule-supreme-by-giraffes-giraffes',
      filePathStem: '/songs/when-the-catholic-girls-go-camping-the-nicotine-vampires-rule-supreme-by-giraffes-giraffes',
      outputFormat: 'fs',
      behavior: [TemplateBehavior],
      serverlessUrls: null,
      _logger: [ConsoleLogger],
      _templateRender: [TemplateRender],
      _frontMatter: [Object],
      _usePermalinkRoot: undefined,
      inputContent: [Promise],
      readingPromise: [Promise],
      _frontMatterDataCache: [Promise],
      _dataCache: [Object]
    },
    data: {
      me: [Object],
      metadata: [Object],
      site: [Object],
      eleventy: [Object],
      pkg: [Object],
      layout: 'song.11ty.js',
      description: '',
      tags: [Array],
      date: 2023-08-22T16:39:26.000Z,
      title: 'When the Catholic Girls Go Camping, the Nicotine Vampires Rule Supreme. by Giraffes? Giraffes!',
      public: true,
      artists: [Array],
      songtitle: 'When the Catholic Girls Go Camping, the Nicotine Vampires Rule Supreme.',
      album: 'More Skin With Milk-Mouth (2015 Remaster)',
      featuredImage: 'when-the-catholic-girls-go-camping-the-nicotine-vampires-rule-supreme-by-giraffes-giraffes.jpeg',
      featuredImageCredit: 'Image is used from album for review purposes.',
      featuredImageLink: 'when-the-catholic-girls-go-camping-the-nicotine-vampires-rule-supreme-by-giraffes-giraffes.jpeg',
      featuredImageAlt: '',
      playlists: [Array],
      youtube: 'https://www.youtube.com/watch?v=H1WvoyvhR9U',
      spotify: 'https://open.spotify.com/track/54oLh4FPlncvCGOSi1DDCF',
      soundcloud: null,
      audiofile: null,
      lastfm: 'https://www.last.fm/music/Giraffes%3F+Giraffes%21/_/When+The+Catholic+Girls+Go+Camping,+The+Nicotine+Vampires+Rule+Supreme.',
      page: [Object],
      collections: [Object]
    },
    page: {
      date: 2023-08-22T16:39:26.000Z,
      inputPath: './src/songs/when-the-catholic-girls-go-camping-the-nicotine-vampires-rule-supreme-by-giraffes-giraffes.md',
      fileSlug: 'when-the-catholic-girls-go-camping-the-nicotine-vampires-rule-supreme-by-giraffes-giraffes',
      filePathStem: '/songs/when-the-catholic-girls-go-camping-the-nicotine-vampires-rule-supreme-by-giraffes-giraffes',
      outputFileExtension: 'html',
      templateSyntax: 'liquid,md',
      url: '/songs/when-the-catholic-girls-go-camping-the-nicotine-vampires-rule-supreme-by-giraffes-giraffes/',
      outputPath: 'docs/songs/when-the-catholic-girls-go-camping-the-nicotine-vampires-rule-supreme-by-giraffes-giraffes/index.html'
    },
    inputPath: './src/songs/when-the-catholic-girls-go-camping-the-nicotine-vampires-rule-supreme-by-giraffes-giraffes.md',
    fileSlug: 'when-the-catholic-girls-go-camping-the-nicotine-vampires-rule-supreme-by-giraffes-giraffes',
    filePathStem: '/songs/when-the-catholic-girls-go-camping-the-nicotine-vampires-rule-supreme-by-giraffes-giraffes',
    date: 2023-08-22T16:39:26.000Z,
    outputPath: 'docs/songs/when-the-catholic-girls-go-camping-the-nicotine-vampires-rule-supreme-by-giraffes-giraffes/index.html',
    url: '/songs/when-the-catholic-girls-go-camping-the-nicotine-vampires-rule-supreme-by-giraffes-giraffes/',
    templateContent: [Getter/Setter],
    content: [Getter]
  },
  {
    template: Template {
      _config: [TemplateConfig],
      _configOptions: [Object],
      inputPath: './src/songs/infected-mushroom-remix-by-berry-sakharof-and-infected-mushroom.md',
      inputDir: 'src',
      parsed: [Object],
      extraOutputSubdirectory: '',
      outputDir: 'docs',
      _extensionMap: [EleventyExtensionMap],
      linters: [],
      transforms: [],
      templateData: [TemplateData],
      isVerbose: false,
      isDryRun: false,
      writeCount: 0,
      fileSlug: [TemplateFileSlug],
      fileSlugStr: 'infected-mushroom-remix-by-berry-sakharof-and-infected-mushroom',
      filePathStem: '/songs/infected-mushroom-remix-by-berry-sakharof-and-infected-mushroom',
      outputFormat: 'fs',
      behavior: [TemplateBehavior],
      serverlessUrls: null,
      _logger: [ConsoleLogger],
      _templateRender: [TemplateRender],
      _frontMatter: [Object],
      _usePermalinkRoot: undefined,
      inputContent: [Promise],
      readingPromise: [Promise],
      _frontMatterDataCache: [Promise],
      _dataCache: [Object]
    },
    data: {
      me: [Object],
      metadata: [Object],
      site: [Object],
      eleventy: [Object],
      pkg: [Object],
      layout: 'song.11ty.js',
      description: '',
      tags: [Array],
      date: 2023-08-22T16:39:36.000Z,
      title: 'יומולדת - Infected Mushroom Remix by Berry Sakharof and Infected Mushroom',
      public: true,
      artists: [Array],
      songtitle: 'יומולדת - Infected Mushroom Remix',
      album: 'Birthday',
      featuredImage: 'infected-mushroom-remix-by-berry-sakharof-and-infected-mushroom.jpeg',
      featuredImageCredit: 'Image is used from album for review purposes.',
      featuredImageLink: 'infected-mushroom-remix-by-berry-sakharof-and-infected-mushroom.jpeg',
      featuredImageAlt: '',
      playlists: [Array],
      youtube: 'https://www.youtube.com/watch?v=5s-YVe66kv8',
      spotify: 'https://open.spotify.com/track/3jtXHIznBsnK5qPLVAdXbv',
      soundcloud: null,
      audiofile: null,
      lastfm: 'https://www.last.fm/music/Berry+Sakharof/_/%D7%99%D7%95%D7%9E%D7%95%D7%9C%D7%93%D7%AA+-+Infected+Mushroom+Remix',
      page: [Object],
      collections: [Object]
    },
    page: {
      date: 2023-08-22T16:39:36.000Z,
      inputPath: './src/songs/infected-mushroom-remix-by-berry-sakharof-and-infected-mushroom.md',
      fileSlug: 'infected-mushroom-remix-by-berry-sakharof-and-infected-mushroom',
      filePathStem: '/songs/infected-mushroom-remix-by-berry-sakharof-and-infected-mushroom',
      outputFileExtension: 'html',
      templateSyntax: 'liquid,md',
      url: '/songs/infected-mushroom-remix-by-berry-sakharof-and-infected-mushroom/',
      outputPath: 'docs/songs/infected-mushroom-remix-by-berry-sakharof-and-infected-mushroom/index.html'
    },
    inputPath: './src/songs/infected-mushroom-remix-by-berry-sakharof-and-infected-mushroom.md',
    fileSlug: 'infected-mushroom-remix-by-berry-sakharof-and-infected-mushroom',
    filePathStem: '/songs/infected-mushroom-remix-by-berry-sakharof-and-infected-mushroom',
    date: 2023-08-22T16:39:36.000Z,
    outputPath: 'docs/songs/infected-mushroom-remix-by-berry-sakharof-and-infected-mushroom/index.html',
    url: '/songs/infected-mushroom-remix-by-berry-sakharof-and-infected-mushroom/',
    templateContent: [Getter/Setter],
    content: [Getter]
  },
  {
    template: Template {
      _config: [TemplateConfig],
      _configOptions: [Object],
      inputPath: './src/songs/air-fire-water-earth-by-heather-christian.md',
      inputDir: 'src',
      parsed: [Object],
      extraOutputSubdirectory: '',
      outputDir: 'docs',
      _extensionMap: [EleventyExtensionMap],
      linters: [],
      transforms: [],
      templateData: [TemplateData],
      isVerbose: false,
      isDryRun: false,
      writeCount: 0,
      fileSlug: [TemplateFileSlug],
      fileSlugStr: 'air-fire-water-earth-by-heather-christian',
      filePathStem: '/songs/air-fire-water-earth-by-heather-christian',
      outputFormat: 'fs',
      behavior: [TemplateBehavior],
      serverlessUrls: null,
      _logger: [ConsoleLogger],
      _templateRender: [TemplateRender],
      _frontMatter: [Object],
      _usePermalinkRoot: undefined,
      inputContent: [Promise],
      readingPromise: [Promise],
      _frontMatterDataCache: [Promise],
      _dataCache: [Object]
    },
    data: {
      me: [Object],
      metadata: [Object],
      site: [Object],
      eleventy: [Object],
      pkg: [Object],
      layout: 'song.11ty.js',
      description: '',
      tags: [Array],
      date: 2023-08-22T16:39:55.000Z,
      title: 'Air Fire Water Earth by Heather Christian',
      public: true,
      artists: [Array],
      songtitle: 'Air Fire Water Earth',
      album: 'The Craft: Legacy (Original Motion Picture Soundtrack)',
      featuredImage: 'air-fire-water-earth-by-heather-christian.jpeg',
      featuredImageCredit: 'Image is used from album for review purposes.',
      featuredImageLink: 'air-fire-water-earth-by-heather-christian.jpeg',
      featuredImageAlt: '',
      playlists: [Array],
      youtube: 'https://www.youtube.com/watch?v=5DM2YT06_Z0',
      spotify: 'https://open.spotify.com/track/4FpYOA5LJtfZBoQpRnlJbm',
      soundcloud: null,
      audiofile: null,
      lastfm: 'https://www.last.fm/music/Heather+Christian/_/Air+Fire+Water+Earth',
      page: [Object],
      collections: [Object]
    },
    page: {
      date: 2023-08-22T16:39:55.000Z,
      inputPath: './src/songs/air-fire-water-earth-by-heather-christian.md',
      fileSlug: 'air-fire-water-earth-by-heather-christian',
      filePathStem: '/songs/air-fire-water-earth-by-heather-christian',
      outputFileExtension: 'html',
      templateSyntax: 'liquid,md',
      url: '/songs/air-fire-water-earth-by-heather-christian/',
      outputPath: 'docs/songs/air-fire-water-earth-by-heather-christian/index.html'
    },
    inputPath: './src/songs/air-fire-water-earth-by-heather-christian.md',
    fileSlug: 'air-fire-water-earth-by-heather-christian',
    filePathStem: '/songs/air-fire-water-earth-by-heather-christian',
    date: 2023-08-22T16:39:55.000Z,
    outputPath: 'docs/songs/air-fire-water-earth-by-heather-christian/index.html',
    url: '/songs/air-fire-water-earth-by-heather-christian/',
    templateContent: [Getter/Setter],
    content: [Getter]
  },
  {
    template: Template {
      _config: [TemplateConfig],
      _configOptions: [Object],
      inputPath: './src/songs/kiss-the-sky-by-shawn-lees-ping-pong-orchestra-vs-nino-moschella.md',
      inputDir: 'src',
      parsed: [Object],
      extraOutputSubdirectory: '',
      outputDir: 'docs',
      _extensionMap: [EleventyExtensionMap],
      linters: [],
      transforms: [],
      templateData: [TemplateData],
      isVerbose: false,
      isDryRun: false,
      writeCount: 0,
      fileSlug: [TemplateFileSlug],
      fileSlugStr: 'kiss-the-sky-by-shawn-lees-ping-pong-orchestra-vs-nino-moschella',
      filePathStem: '/songs/kiss-the-sky-by-shawn-lees-ping-pong-orchestra-vs-nino-moschella',
      outputFormat: 'fs',
      behavior: [TemplateBehavior],
      serverlessUrls: null,
      _logger: [ConsoleLogger],
      _templateRender: [TemplateRender],
      _frontMatter: [Object],
      _usePermalinkRoot: undefined,
      inputContent: [Promise],
      readingPromise: [Promise],
      _frontMatterDataCache: [Promise],
      _dataCache: [Object]
    },
    data: {
      me: [Object],
      metadata: [Object],
      site: [Object],
      eleventy: [Object],
      pkg: [Object],
      layout: 'song.11ty.js',
      description: '',
      tags: [Array],
      date: 2023-08-22T16:57:41.000Z,
      title: "Kiss the Sky by Shawn Lee's Ping Pong Orchestra vs. Nino Moschella",
      public: true,
      artists: [Array],
      songtitle: 'Kiss the Sky',
      album: 'Kiss the Sky EP',
      featuredImage: 'kiss-the-sky-by-shawn-lees-ping-pong-orchestra-vs-nino-moschella.jpeg',
      featuredImageCredit: 'Image is used from album for review purposes.',
      featuredImageLink: 'kiss-the-sky-by-shawn-lees-ping-pong-orchestra-vs-nino-moschella.jpeg',
      featuredImageAlt: '',
      playlists: [Array],
      youtube: 'https://www.youtube.com/watch?v=3pHQuCezmLE',
      spotify: 'https://open.spotify.com/track/17zlPFbT0pzb2FxNqK2Bcm',
      soundcloud: null,
      audiofile: null,
      lastfm: 'https://www.last.fm/music/Shawn+Lee%27s+Ping+Pong+Orchestra/_/Kiss+the+Sky',
      page: [Object],
      collections: [Object]
    },
    page: {
      date: 2023-08-22T16:57:41.000Z,
      inputPath: './src/songs/kiss-the-sky-by-shawn-lees-ping-pong-orchestra-vs-nino-moschella.md',
      fileSlug: 'kiss-the-sky-by-shawn-lees-ping-pong-orchestra-vs-nino-moschella',
      filePathStem: '/songs/kiss-the-sky-by-shawn-lees-ping-pong-orchestra-vs-nino-moschella',
      outputFileExtension: 'html',
      templateSyntax: 'liquid,md',
      url: '/songs/kiss-the-sky-by-shawn-lees-ping-pong-orchestra-vs-nino-moschella/',
      outputPath: 'docs/songs/kiss-the-sky-by-shawn-lees-ping-pong-orchestra-vs-nino-moschella/index.html'
    },
    inputPath: './src/songs/kiss-the-sky-by-shawn-lees-ping-pong-orchestra-vs-nino-moschella.md',
    fileSlug: 'kiss-the-sky-by-shawn-lees-ping-pong-orchestra-vs-nino-moschella',
    filePathStem: '/songs/kiss-the-sky-by-shawn-lees-ping-pong-orchestra-vs-nino-moschella',
    date: 2023-08-22T16:57:41.000Z,
    outputPath: 'docs/songs/kiss-the-sky-by-shawn-lees-ping-pong-orchestra-vs-nino-moschella/index.html',
    url: '/songs/kiss-the-sky-by-shawn-lees-ping-pong-orchestra-vs-nino-moschella/',
    templateContent: [Getter/Setter],
    content: [Getter]
  },
  {
    template: Template {
      _config: [TemplateConfig],
      _configOptions: [Object],
      inputPath: './src/songs/its-okay-to-punch-nazis-by-cheap-perfume.md',
      inputDir: 'src',
      parsed: [Object],
      extraOutputSubdirectory: '',
      outputDir: 'docs',
      _extensionMap: [EleventyExtensionMap],
      linters: [],
      transforms: [],
      templateData: [TemplateData],
      isVerbose: false,
      isDryRun: false,
      writeCount: 0,
      fileSlug: [TemplateFileSlug],
      fileSlugStr: 'its-okay-to-punch-nazis-by-cheap-perfume',
      filePathStem: '/songs/its-okay-to-punch-nazis-by-cheap-perfume',
      outputFormat: 'fs',
      behavior: [TemplateBehavior],
      serverlessUrls: null,
      _logger: [ConsoleLogger],
      _templateRender: [TemplateRender],
      _frontMatter: [Object],
      _usePermalinkRoot: undefined,
      inputContent: [Promise],
      readingPromise: [Promise],
      _frontMatterDataCache: [Promise],
      _dataCache: [Object]
    },
    data: {
      me: [Object],
      metadata: [Object],
      site: [Object],
      eleventy: [Object],
      pkg: [Object],
      layout: 'song.11ty.js',
      description: '',
      tags: [Array],
      date: 2023-08-30T21:05:59.000Z,
      title: "It's Okay (To Punch Nazis) by Cheap Perfume",
      public: true,
      artists: [Array],
      songtitle: "It's Okay (To Punch Nazis)",
      album: "It's Okay (To Punch Nazis)",
      featuredImage: 'its-okay-to-punch-nazis-by-cheap-perfume.jpeg',
      featuredImageCredit: 'Image is used from album for review purposes.',
      featuredImageLink: 'its-okay-to-punch-nazis-by-cheap-perfume.jpeg',
      featuredImageAlt: '',
      playlists: [Array],
      youtube: 'https://www.youtube.com/watch?v=-sOSr7n_8YU',
      spotify: 'https://open.spotify.com/track/24BexGKYvuQPv2W1ObGYmw',
      soundcloud: null,
      audiofile: null,
      lastfm: 'https://www.last.fm/music/Cheap+Perfume/_/It%27s+Okay+(To+Punch+Nazis)',
      page: [Object],
      collections: [Object]
    },
    page: {
      date: 2023-08-30T21:05:59.000Z,
      inputPath: './src/songs/its-okay-to-punch-nazis-by-cheap-perfume.md',
      fileSlug: 'its-okay-to-punch-nazis-by-cheap-perfume',
      filePathStem: '/songs/its-okay-to-punch-nazis-by-cheap-perfume',
      outputFileExtension: 'html',
      templateSyntax: 'liquid,md',
      url: '/songs/its-okay-to-punch-nazis-by-cheap-perfume/',
      outputPath: 'docs/songs/its-okay-to-punch-nazis-by-cheap-perfume/index.html'
    },
    inputPath: './src/songs/its-okay-to-punch-nazis-by-cheap-perfume.md',
    fileSlug: 'its-okay-to-punch-nazis-by-cheap-perfume',
    filePathStem: '/songs/its-okay-to-punch-nazis-by-cheap-perfume',
    date: 2023-08-30T21:05:59.000Z,
    outputPath: 'docs/songs/its-okay-to-punch-nazis-by-cheap-perfume/index.html',
    url: '/songs/its-okay-to-punch-nazis-by-cheap-perfume/',
    templateContent: [Getter/Setter],
    content: [Getter]
  },
  {
    template: Template {
      _config: [TemplateConfig],
      _configOptions: [Object],
      inputPath: './src/songs/im-downright-amazed-at-what-i-can-destroy-with-just-a-hammer-by-atom-and-his-package.md',
      inputDir: 'src',
      parsed: [Object],
      extraOutputSubdirectory: '',
      outputDir: 'docs',
      _extensionMap: [EleventyExtensionMap],
      linters: [],
      transforms: [],
      templateData: [TemplateData],
      isVerbose: false,
      isDryRun: false,
      writeCount: 0,
      fileSlug: [TemplateFileSlug],
      fileSlugStr: 'im-downright-amazed-at-what-i-can-destroy-with-just-a-hammer-by-atom-and-his-package',
      filePathStem: '/songs/im-downright-amazed-at-what-i-can-destroy-with-just-a-hammer-by-atom-and-his-package',
      outputFormat: 'fs',
      behavior: [TemplateBehavior],
      serverlessUrls: null,
      _logger: [ConsoleLogger],
      _templateRender: [TemplateRender],
      _frontMatter: [Object],
      _usePermalinkRoot: undefined,
      inputContent: [Promise],
      readingPromise: [Promise],
      _frontMatterDataCache: [Promise],
      _dataCache: [Object]
    },
    data: {
      me: [Object],
      metadata: [Object],
      site: [Object],
      eleventy: [Object],
      pkg: [Object],
      layout: 'song.11ty.js',
      description: '',
      tags: [Array],
      date: 2023-08-30T21:06:29.000Z,
      title: 'I’m Downright Amazed At What I Can Destroy With Just A Hammer by Atom And His Package',
      public: true,
      artists: [Array],
      songtitle: 'I’m Downright Amazed At What I Can Destroy With Just A Hammer',
      album: 'Attention! Blah Blah Blah',
      featuredImage: 'im-downright-amazed-at-what-i-can-destroy-with-just-a-hammer-by-atom-and-his-package.jpeg',
      featuredImageCredit: 'Image is used from album for review purposes.',
      featuredImageLink: 'im-downright-amazed-at-what-i-can-destroy-with-just-a-hammer-by-atom-and-his-package.jpeg',
      featuredImageAlt: '',
      playlists: [Array],
      youtube: 'https://www.youtube.com/watch?v=mnMmRVfybN4',
      spotify: 'https://open.spotify.com/track/0Ln29RgpKG8QvpECfW5n1j',
      soundcloud: null,
      audiofile: null,
      lastfm: 'https://www.last.fm/music/Atom+and+His+Package/_/I%E2%80%99m+Downright+Amazed+At+What+I+Can+Destroy+With+Just+A+Hammer',
      page: [Object],
      collections: [Object]
    },
    page: {
      date: 2023-08-30T21:06:29.000Z,
      inputPath: './src/songs/im-downright-amazed-at-what-i-can-destroy-with-just-a-hammer-by-atom-and-his-package.md',
      fileSlug: 'im-downright-amazed-at-what-i-can-destroy-with-just-a-hammer-by-atom-and-his-package',
      filePathStem: '/songs/im-downright-amazed-at-what-i-can-destroy-with-just-a-hammer-by-atom-and-his-package',
      outputFileExtension: 'html',
      templateSyntax: 'liquid,md',
      url: '/songs/im-downright-amazed-at-what-i-can-destroy-with-just-a-hammer-by-atom-and-his-package/',
      outputPath: 'docs/songs/im-downright-amazed-at-what-i-can-destroy-with-just-a-hammer-by-atom-and-his-package/index.html'
    },
    inputPath: './src/songs/im-downright-amazed-at-what-i-can-destroy-with-just-a-hammer-by-atom-and-his-package.md',
    fileSlug: 'im-downright-amazed-at-what-i-can-destroy-with-just-a-hammer-by-atom-and-his-package',
    filePathStem: '/songs/im-downright-amazed-at-what-i-can-destroy-with-just-a-hammer-by-atom-and-his-package',
    date: 2023-08-30T21:06:29.000Z,
    outputPath: 'docs/songs/im-downright-amazed-at-what-i-can-destroy-with-just-a-hammer-by-atom-and-his-package/index.html',
    url: '/songs/im-downright-amazed-at-what-i-can-destroy-with-just-a-hammer-by-atom-and-his-package/',
    templateContent: [Getter/Setter],
    content: [Getter]
  },
  {
    template: Template {
      _config: [TemplateConfig],
      _configOptions: [Object],
      inputPath: './src/songs/su-beso-de-plata-redux-by-carlos-viola.md',
      inputDir: 'src',
      parsed: [Object],
      extraOutputSubdirectory: '',
      outputDir: 'docs',
      _extensionMap: [EleventyExtensionMap],
      linters: [],
      transforms: [],
      templateData: [TemplateData],
      isVerbose: false,
      isDryRun: false,
      writeCount: 0,
      fileSlug: [TemplateFileSlug],
      fileSlugStr: 'su-beso-de-plata-redux-by-carlos-viola',
      filePathStem: '/songs/su-beso-de-plata-redux-by-carlos-viola',
      outputFormat: 'fs',
      behavior: [TemplateBehavior],
      serverlessUrls: null,
      _logger: [ConsoleLogger],
      _templateRender: [TemplateRender],
      _frontMatter: [Object],
      _usePermalinkRoot: undefined,
      inputContent: [Promise],
      readingPromise: [Promise],
      _frontMatterDataCache: [Promise],
      _dataCache: [Object]
    },
    data: {
      me: [Object],
      metadata: [Object],
      site: [Object],
      eleventy: [Object],
      pkg: [Object],
      layout: 'song.11ty.js',
      description: '',
      tags: [Array],
      date: 2023-08-30T21:06:40.000Z,
      title: 'Su Beso de Plata - Redux by Carlos Viola',
      public: true,
      artists: [Array],
      songtitle: 'Su Beso de Plata - Redux',
      album: 'Blasphemous: Wounds of Eventide (Original Game Soundtrack)',
      featuredImage: 'su-beso-de-plata-redux-by-carlos-viola.jpeg',
      featuredImageCredit: 'Image is used from album for review purposes.',
      featuredImageLink: 'su-beso-de-plata-redux-by-carlos-viola.jpeg',
      featuredImageAlt: '',
      playlists: [Array],
      youtube: 'https://www.youtube.com/watch?v=CO218kSZoeA',
      spotify: 'https://open.spotify.com/track/35qkwnnlbohFTDGUaOKhCT',
      soundcloud: null,
      audiofile: null,
      lastfm: 'https://www.last.fm/music/Carlos+Viola/_/Su+Beso+de+Plata+-+Redux',
      page: [Object],
      collections: [Object]
    },
    page: {
      date: 2023-08-30T21:06:40.000Z,
      inputPath: './src/songs/su-beso-de-plata-redux-by-carlos-viola.md',
      fileSlug: 'su-beso-de-plata-redux-by-carlos-viola',
      filePathStem: '/songs/su-beso-de-plata-redux-by-carlos-viola',
      outputFileExtension: 'html',
      templateSyntax: 'liquid,md',
      url: '/songs/su-beso-de-plata-redux-by-carlos-viola/',
      outputPath: 'docs/songs/su-beso-de-plata-redux-by-carlos-viola/index.html'
    },
    inputPath: './src/songs/su-beso-de-plata-redux-by-carlos-viola.md',
    fileSlug: 'su-beso-de-plata-redux-by-carlos-viola',
    filePathStem: '/songs/su-beso-de-plata-redux-by-carlos-viola',
    date: 2023-08-30T21:06:40.000Z,
    outputPath: 'docs/songs/su-beso-de-plata-redux-by-carlos-viola/index.html',
    url: '/songs/su-beso-de-plata-redux-by-carlos-viola/',
    templateContent: [Getter/Setter],
    content: [Getter]
  },
  {
    template: Template {
      _config: [TemplateConfig],
      _configOptions: [Object],
      inputPath: './src/songs/the-root-by-magna-carda.md',
      inputDir: 'src',
      parsed: [Object],
      extraOutputSubdirectory: '',
      outputDir: 'docs',
      _extensionMap: [EleventyExtensionMap],
      linters: [],
      transforms: [],
      templateData: [TemplateData],
      isVerbose: false,
      isDryRun: false,
      writeCount: 0,
      fileSlug: [TemplateFileSlug],
      fileSlugStr: 'the-root-by-magna-carda',
      filePathStem: '/songs/the-root-by-magna-carda',
      outputFormat: 'fs',
      behavior: [TemplateBehavior],
      serverlessUrls: null,
      _logger: [ConsoleLogger],
      _templateRender: [TemplateRender],
      _frontMatter: [Object],
      _usePermalinkRoot: undefined,
      inputContent: [Promise],
      readingPromise: [Promise],
      _frontMatterDataCache: [Promise],
      _dataCache: [Object]
    },
    data: {
      me: [Object],
      metadata: [Object],
      site: [Object],
      eleventy: [Object],
      pkg: [Object],
      layout: 'song.11ty.js',
      description: '',
      tags: [Array],
      date: 2023-08-30T21:06:51.000Z,
      title: 'The Root by Magna Carda',
      public: true,
      artists: [Array],
      songtitle: 'The Root',
      album: 'Cirqlation',
      featuredImage: 'the-root-by-magna-carda.jpeg',
      featuredImageCredit: 'Image is used from album for review purposes.',
      featuredImageLink: 'the-root-by-magna-carda.jpeg',
      featuredImageAlt: '',
      playlists: [Array],
      youtube: 'https://www.youtube.com/watch?v=Mbzqfdqnt_o',
      spotify: 'https://open.spotify.com/track/21sficAs0W3Swr2kyQ75ps',
      soundcloud: null,
      audiofile: null,
      lastfm: 'https://www.last.fm/music/Magna+Carda/_/The+Root',
      page: [Object],
      collections: [Object]
    },
    page: {
      date: 2023-08-30T21:06:51.000Z,
      inputPath: './src/songs/the-root-by-magna-carda.md',
      fileSlug: 'the-root-by-magna-carda',
      filePathStem: '/songs/the-root-by-magna-carda',
      outputFileExtension: 'html',
      templateSyntax: 'liquid,md',
      url: '/songs/the-root-by-magna-carda/',
      outputPath: 'docs/songs/the-root-by-magna-carda/index.html'
    },
    inputPath: './src/songs/the-root-by-magna-carda.md',
    fileSlug: 'the-root-by-magna-carda',
    filePathStem: '/songs/the-root-by-magna-carda',
    date: 2023-08-30T21:06:51.000Z,
    outputPath: 'docs/songs/the-root-by-magna-carda/index.html',
    url: '/songs/the-root-by-magna-carda/',
    templateContent: [Getter/Setter],
    content: [Getter]
  },
  {
    template: Template {
      _config: [TemplateConfig],
      _configOptions: [Object],
      inputPath: './src/songs/new-york-by-angel-haze.md',
      inputDir: 'src',
      parsed: [Object],
      extraOutputSubdirectory: '',
      outputDir: 'docs',
      _extensionMap: [EleventyExtensionMap],
      linters: [],
      transforms: [],
      templateData: [TemplateData],
      isVerbose: false,
      isDryRun: false,
      writeCount: 0,
      fileSlug: [TemplateFileSlug],
      fileSlugStr: 'new-york-by-angel-haze',
      filePathStem: '/songs/new-york-by-angel-haze',
      outputFormat: 'fs',
      behavior: [TemplateBehavior],
      serverlessUrls: null,
      _logger: [ConsoleLogger],
      _templateRender: [TemplateRender],
      _frontMatter: [Object],
      _usePermalinkRoot: undefined,
      inputContent: [Promise],
      readingPromise: [Promise],
      _frontMatterDataCache: [Promise],
      _dataCache: [Object]
    },
    data: {
      me: [Object],
      metadata: [Object],
      site: [Object],
      eleventy: [Object],
      pkg: [Object],
      layout: 'song.11ty.js',
      description: '',
      tags: [Array],
      date: 2023-08-31T15:40:54.000Z,
      title: 'New York by Angel Haze',
      public: true,
      artists: [Array],
      songtitle: 'New York',
      album: 'Dirty Gold (Deluxe)',
      featuredImage: 'new-york-by-angel-haze.jpeg',
      featuredImageCredit: 'Image is used from album for review purposes.',
      featuredImageLink: 'new-york-by-angel-haze.jpeg',
      featuredImageAlt: '',
      playlists: [Array],
      youtube: 'https://www.youtube.com/watch?v=4hKP5ljDar8',
      spotify: 'https://open.spotify.com/track/15mKdoeoLQr6F8cFdko7Aa',
      soundcloud: null,
      audiofile: null,
      lastfm: 'https://www.last.fm/music/Angel+Haze/_/New+York',
      page: [Object],
      collections: [Object]
    },
    page: {
      date: 2023-08-31T15:40:54.000Z,
      inputPath: './src/songs/new-york-by-angel-haze.md',
      fileSlug: 'new-york-by-angel-haze',
      filePathStem: '/songs/new-york-by-angel-haze',
      outputFileExtension: 'html',
      templateSyntax: 'liquid,md',
      url: '/songs/new-york-by-angel-haze/',
      outputPath: 'docs/songs/new-york-by-angel-haze/index.html'
    },
    inputPath: './src/songs/new-york-by-angel-haze.md',
    fileSlug: 'new-york-by-angel-haze',
    filePathStem: '/songs/new-york-by-angel-haze',
    date: 2023-08-31T15:40:54.000Z,
    outputPath: 'docs/songs/new-york-by-angel-haze/index.html',
    url: '/songs/new-york-by-angel-haze/',
    templateContent: [Getter/Setter],
    content: [Getter]
  }
]
 * 
*/
