name: Eleventy Build

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_GITHUB_RUN_ID: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "21"
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Install Sharp
        run: npm install --include=optional sharp

      - name: Install dependencies
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Upload artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          path: ./docs
          name: github-pages

 
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}   
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./docs
      - name: Verify artifact download
        run: ls -l ./docs          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
